### ISSUE TITLE
Shortcut doesn't work on Windows

### ISSUE THREAD

**Issue by garrrikkotua** [zzzze/tauri-plugin-spotlight#1]
Really nice project, thanks!

Unfortunately, can't make shortcut work on Windows (e.g show / close app). As far as I see in code, non MacOS platforms are supported.

**Comment by garrrikkotua** [comment]
hide function works, but both open / close shortcuts not. I think they are not registered for some reason

**Comment by garrrikkotua** [comment]
@vinzhang0 how can I debug it?

**Comment by zzzze** [comment]
Hi, @garrrikkotua thanks for your contribution. This might be due to some platform-specific issues. I only work on MacOS and Linux environments, so I haven’t run it on Windows yet.
